"use client";

import Image from 'next/image';
import Navbar from '@/components/Navbar';
import BackgroundLines from '@/components/BackgroundLines';
import Footer from '@/components/Footer';

const projects=[['IronChat','A Chatbot','/images/ironchat.svg','https://github.com/sulemangulzar/ironchat'],['Cortex AI Workspace','SWE Team','/images/cortex-workspace.svg','https://github.com/sulemangulzar/cortex-ai-workspace'],['Jarvis','Personal Assistant','/images/jarvis.svg','https://github.com/sulemangulzar/Jarvis']];
export default function AllProjectsPage({darkMode,toggleDarkMode,mobileMenuOpen,setMobileMenuOpen}) { return <div className={darkMode?'dark':''}><div className="min-h-screen bg-white text-neutral-900 transition-colors duration-500 dark:bg-neutral-900 dark:text-neutral-100"><BackgroundLines/><Navbar {...{darkMode,toggleDarkMode,mobileMenuOpen,setMobileMenuOpen}}/><main className="relative z-10 mx-auto min-h-[calc(100vh-140px)] w-[calc(100%-40px)] max-w-[830px] py-8 sm:py-10"><h1 className="mb-2 text-3xl font-bold tracking-[-.05em] sm:text-4xl">Our Projects</h1><p className="mb-7 max-w-[780px] text-lg leading-relaxed text-neutral-500 dark:text-neutral-400">Explore the AI-powered applications I&apos;m building across intelligent systems, developer tools, and personal assistants.</p><div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">{projects.map(([title,description,image,link])=><a key={title} href={link} target="_blank" rel="noopener noreferrer" className="rounded-2xl border border-dashed border-neutral-300 bg-white/40 p-2.5 transition hover:-translate-y-1 hover:bg-white dark:border-neutral-700 dark:bg-neutral-900/40 dark:hover:bg-neutral-800"><Image src={image} alt={`${title} project preview`} width={600} height={320} className="h-32 w-full rounded-lg object-cover"/><div className="px-1 py-2"><h2 className="font-bold">{title} <span className="float-right text-neutral-400">↗</span></h2><p className="truncate text-sm text-neutral-500 dark:text-neutral-400">{description}</p></div></a>)}</div></main><Footer/></div></div>; }
