"use client";
import { useState } from 'react';
import { Linkedin, Mail } from 'lucide-react';

export default function Footer() {
  const [emailPromptOpen, setEmailPromptOpen] = useState(false);
  const email = 'suleman_gulzar@icloud.com';
  const iconButton = "flex h-9 w-9 cursor-[url('/cursor.svg')_16_16,_auto] items-center justify-center rounded-full border border-neutral-300 transition hover:scale-110 hover:bg-neutral-100 dark:border-neutral-700 dark:hover:bg-neutral-800";

  return <>
    <footer className="relative z-10 border-t border-neutral-200 dark:border-neutral-800"><div className="mx-auto flex w-[calc(100%-40px)] max-w-[1100px] flex-col gap-3 py-4 text-xs text-neutral-500 sm:flex-row sm:items-center sm:justify-between"><p>© 2026. All rights reserved.</p><div className="flex gap-2"><a href="https://x.com/isulemangulzar" target="_blank" rel="noopener noreferrer" aria-label="X" className={iconButton}><span className="text-base">𝕏</span></a><a href="https://www.linkedin.com/in/sulemangulzar" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn" className={iconButton}><Linkedin size={16}/></a><button type="button" onClick={() => setEmailPromptOpen(true)} aria-label="Email" className={iconButton}><Mail size={16}/></button></div></div></footer>
    {emailPromptOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-neutral-950/40 px-5 backdrop-blur-sm" role="presentation" onClick={() => setEmailPromptOpen(false)}><div role="dialog" aria-modal="true" aria-labelledby="email-dialog-title" className="w-full max-w-sm rounded-2xl border border-neutral-200 bg-white p-6 text-neutral-900 shadow-2xl dark:border-neutral-700 dark:bg-neutral-900 dark:text-neutral-100" onClick={(event) => event.stopPropagation()}><div className="mb-4 flex h-11 w-11 items-center justify-center rounded-full bg-neutral-900 text-white dark:bg-white dark:text-neutral-900"><Mail size={19}/></div><h2 id="email-dialog-title" className="text-lg font-bold">Open your email app?</h2><p className="mt-2 text-sm leading-relaxed text-neutral-500 dark:text-neutral-400">Your email app will open with a new message addressed to:</p><p className="mt-2 break-all rounded-lg bg-neutral-100 px-3 py-2 text-sm font-semibold dark:bg-neutral-800">{email}</p><div className="mt-5 flex justify-end gap-3"><button type="button" onClick={() => setEmailPromptOpen(false)} className="rounded-lg border border-neutral-300 px-4 py-2 text-sm font-semibold transition hover:bg-neutral-100 dark:border-neutral-700 dark:hover:bg-neutral-800">Cancel</button><button type="button" onClick={() => { window.location.href = `mailto:${email}`; setEmailPromptOpen(false); }} className="rounded-lg bg-neutral-900 px-4 py-2 text-sm font-semibold text-white transition hover:bg-neutral-700 dark:bg-white dark:text-neutral-900">Open Email</button></div></div></div>}
  </>;
}
